version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orthoplex
    ports:
      - "5432:5432"
      
  api_v1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    expose:
      - '3000'
    links:
      - db
    depends_on:
      - db

